/**
* @ClassName : HCNA_CustomForecastConstants
* @Description : This is the Constant class.This class performs the functionality of storing constant values.
* @Author : Albin Deni Arul
* @Last Modified : 25/02/2014
* @Discussionpoints : No Information
**/
public class HCNA_CustomForecastConstants{
    public static  final string filterForAccount = 'Account';
    public static  final string filterForOpportunity = 'Opportunity';
    public static  final string filterForUser = 'User';
    public static  final string recordTypeObject= 'RecordType';
    
    /**  
    * @Description : Constructor
    **/
    public HCNA_CustomForecastConstants(){    
    }
    
}