/**
@Classname :       HCNA_CustomForecastConstants_test
@Description :     This test class is written to test the Apex class HCNA_CustomForecastConstants
@Author:           Harmeet
@Last Modified:    4/30/2014
**/

@isTest(SeeAllData=false)
private class HCNA_CustomForecastConstants_test{

    /**    
    * @Description : Test method to invoke HCNA_CustomForecastConstants constructor to store constant values
    **/
    public static testMethod void test_HCNA_CustomForecastConstants() {
        test.starttest();
        HCNA_CustomForecastConstants obj = new HCNA_CustomForecastConstants();
        test.stoptest(); 
    }
}