/**
@Classname :       M2O_UserLoginInfoControllerTest
@Description :     This test class is written to test the Apex class M2O_UserLoginInfoController. 
@Author:           Ramita
@Last Modified:    1/09/2015
**/
@isTest(SeeAllData=false)
public class M2O_UserLoginInfoControllerTest{
    
    static TestMethod void test_M2O_UserLoginInfoControllerConstructor(){
        /*Profile hcProfileId = M2O_UserTestDataUtility.getM2OSystemAdminProfileId();
        User runAsUser = M2O_UserTestDataUtility.getHCUserRecord(hcProfileId.Id);
        insert runAsUser;
        M2O_UserLoginInfoController1 controllerObj = new M2O_UserLoginInfoController1 ();*/
    }
}