/*****
*Description :- This controller is being used by User Login page.
*Author :- Somdev Bhattacharyya
*****/

public class M2O_UserLoginInfoController1 {

    /*
    public list<AuthSession> concurrentLoginList {get; set;}
    public list<LoginHistory> allLoginList {get; set;}
    public LoginHistory userLoginHistory {get; set;}
    public string allLogins{get;set;}
    public string activeLogins{get;set;}
    public String currentUsrId {get; set;}
    public AuthSession userLogin;
    public User lastLogin{get;set;}

    public  M2O_UserLoginInfoController1() {
        M2O_UserLoginDAO daoHelper = new M2O_UserLoginDAO();
        currentUsrId =UserInfo.getUserId();
        lastLogin = daoHelper.getCurrentUserInfo(currentUsrId);
        allLoginList=daoHelper.getAllLoginList(currentUsrId);
        userLogin=daoHelper.getUserLogin(currentUsrId);
        Time time1 =userLogin.CreatedDate.time();
        userLoginHistory=daoHelper.getuserLoginHistory(userLogin,currentUsrId);
        concurrentLoginList =daoHelper.getConcurrentLoginList(currentUsrId);
        allLogins = URL.getSalesforceBaseUrl().toExternalForm()+'/apex/M2O_UserAllLogins';
        activeLogins = URL.getSalesforceBaseUrl().toExternalForm()+'/apex/M2O_ConcurrentLogin';
    }    */
}