/*
    @author         Rahul Shaw <rahul.shaw@wipro.com>
    @class          ScheduledMerge
    @abstract       Calls Role_AuditTrail class
    @since          2012.03.20
    @discussion     Schedule class to capture changes in role hierarchy
*/
global class scheduledMerge implements Schedulable{
   global void execute(SchedulableContext SC) {
  /*  Role_AuditTrail r = new Role_AuditTrail(); 
      r.test();*/
        }
}